name: (Auto) Deploy to Multidev
on: 
  push:
    # branches-ignore: ["master", "main"]
    branches:
      - 'md*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - uses: actions/checkout@v2
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ vars.SSH_CONFIG }}
        known_hosts: ${{ vars.KNOWN_HOSTS }}
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
    - name: Deployment Processing
      id: branch-processor
      env:
        CI_BRANCH: ${{ github.ref_name }}
        TERMINUS_MACHINE_TOKEN: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        PANTHEON_SITE: ${{ vars.PANTHEON_SITE }}
        PANTHEON_REPO: ${{ secrets.PANTHEON_REPO }}
      run: |
        #!/bin/bash
        set +e
        # Push our github code to Pantheon
        echo "Deploying $PANTHEON_SITE to Pantheon $CI_BRANCH branch"
        git fetch --unshallow origin
        git push --force $PANTHEON_REPO $CI_BRANCH
        echo "URL_FRAGMENT=dev" >> $GITHUB_OUTPUT
        terminus env:info $PANTHEON_SITE.$CI_BRANCH --quiet
        command_status=$?
        echo "URL_FRAGMENT=${CI_BRANCH}" >> $GITHUB_OUTPUT
        if [ $command_status -ne 0 ]; then
          echo "${CI_BRANCH} Multidev does not exist. Attempting to create."
          terminus multidev:create $PANTHEON_SITE.dev $CI_BRANCH
        else
          echo "Multidev environment $CI_BRANCH already exists."
        fi
        echo "MULTIDEV_URL = https://${CI_BRANCH}-${PANTHEON_SITE}.pantheonsite.io" 
    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          Pantheon Multidev updated - https://${{ steps.branch-processor.outputs.URL_FRAGMENT }}-${{ vars.PANTHEON_SITE }}.pantheonsite.io
