name: (Auto) Deploy PR to Pantheon
on:
  pull_request:
    types: [opened,edited,synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - uses: actions/checkout@v2
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ vars.SSH_CONFIG }}
        known_hosts: ${{ vars.KNOWN_HOSTS }}
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
    - name: Deployment Processing
      env:
        CI_BRANCH: ${{ github.ref_name }}
        TERMINUS_MACHINE_TOKEN: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        PANTHEON_SITE: ${{ vars.PANTHEON_SITE }}
        PANTHEON_REPO: ${{ secrets.PANTHEON_REPO }}
        PR_NUM: "pr-${{ github.event.pull_request.number }}"
      run: |
        #!/bin/bash
        set +e
        # Push our github code to Pantheon
        echo "Deploying $PANTHEON_SITE to Pantheon ${PR_NUM} multidev"
        git fetch --unshallow origin
        git branch ${PR_NUM}
        git checkout ${PR_NUM}
        git fetch $PANTHEON_REPO
        git push --force $PANTHEON_REPO ${PR_NUM}
        if [ "$CI_BRANCH" != "master" ]; then
          terminus env:info $PANTHEON_SITE.${PR_NUM} --quiet
          command_status=$?
          if [ $command_status -ne 0 ]; then
            echo "${PR_NUM} Multidev does not exist. Attempting to create."
            terminus multidev:create $PANTHEON_SITE.live ${PR_NUM}
          else
            echo "Multidev environment ${PR_NUM} already exists."
          fi 
          MULTIDEV="https://${PR_NUM}-${PANTHEON_SITE}.pantheonsite.io"
          echo "Multidev: ${MULTIDEV}"
        fi
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Pantheon Multidev updated - https://pr-${{ github.event.pull_request.number }}-${{ vars.PANTHEON_SITE }}.pantheonsite.io"
          })
